baseURL = "https://hsp.sh/"
languageCode = "pl-pl"
title = "Hackerspace Pomorze"
copyright = "CC-BY-SA"

theme = "marvelous-snuffle"

[params]
description = "Hackerspace to miejsce dla osób, którym po prostu się chce!"

[menu]

  [[menu.main]]
    identifier = "Blog"
    name = "Blog"
    url = "/blog/"
    weight = 15

  [[menu.services]]
    identifier = "wiki"
    name = "Wiki"
    url = "https://docs.hsp.sh"
    weight = 15

  [[menu.services]]
    identifier = "forum"
    name = "Forum"
    url = "https://hsp.sh/github"
    weight = 15
    
  [[menu.services]]
    identifier = "git"
    name = "Git"
    url = "https://hsp.sh/github"
    weight = 15

  [[menu.services]]
    identifier = "at"
    name = "Whois"
    url = "https://at.hsp.sh/"
    weight = 15
    
  [[menu.services]]
    identifier = "auth"
    name = "Zaloguj Się"
    url = "https://auth.hsp.sh/"
    weight = 15

  [[menu.social]]
    identifier = "fb"
    name = "Facebook"
    url = "https://hsp.sh/facebook"
    weight = 15

  [[menu.social]]
    identifier = "ig"
    name = "Instagram"
    url = "https://hsp.sh/instagram"
    weight = 15
    
  [[menu.social]]
    identifier = "mstdn"
    name = "Mastodon"
    url = "https://hsp.sh/mastodon"
    weight = 15
